#!/bin/bash

sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install telegram code
cd
mkdir git-tools
cd git-tools

# Kullandigim bazi toollar
git clone https://github.com/fuzzdb-project/fuzzdb.git
git clone https://github.com/lulz3xploit/LittleBrother.git
git clone https://github.com/swisskyrepo/PayloadsAllTheThings.git
git clone https://github.com/sundowndev/PhoneInfoga.git
git clone https://github.com/TheresAFewConors/Sooty.git
git clone https://github.com/m8r0wn/subscraper.git
git clone https://github.com/TheSpeedX/TBomb.git

# VIM Surrounding icin
mkdir -p ~/.vim/pack/tpope/start
cd ~/.vim/pack/tpope/start
git clone https://tpope.io/vim/surround.git
vim -u NONE -c "helptags surround/doc" -c q

# .vimrc icin
cd
wget https://raw.githubusercontent.com/0fatih/Dot-Files/master/.vimrc

# .bashrc icin
https://raw.githubusercontent.com/0fatih/Dot-Files/master/.bashrc

cd Documents
git clone https://github.com/0fatih/Exercise.git
