#!/bin/bash

sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install telegram code
cd
mkdir git-tools
cd git-tools
git clone https://github.com/fuzzdb-project/fuzzdb.git
git clone https://github.com/lulz3xploit/LittleBrother.git
git clone https://github.com/swisskyrepo/PayloadsAllTheThings.git
git clone https://github.com/sundowndev/PhoneInfoga.git
git clone https://github.com/TheresAFewConors/Sooty.git
git clone https://github.com/m8r0wn/subscraper.git
git clone https://github.com/TheSpeedX/TBomb.git
